### ISSUE TITLE
Forest class

### ISSUE THREAD

**Issue by nahurwitz** [rogerhurwitz/arborlife#1]
Create a Forest class!

**Comment by rogerhurwitz** [comment]
Requirements for Forest and Tree from Neil's email:

> Now that Soil has been unleased on the Github world, creating a Forest class with trees and soil make sense. As we chatted about, a forest can be pretty much any shape, but probably best to create a rectangle to start, which could be defined either with existential dimensions or using lat/lon coordinates (dimensions would be more straightforward; lat/lon could tie directly to climate conditions). And assume for now, each square foot (or cell) contains a soil object and spread throughout are tree objects.

> Trees will have many, many attributes, but best to start with just a few – location (needed), age (introduces math functions), and an alive/dead boolean.

> Where are the trees? Each tree’s location will be one cell in the grid of the forest that is set with a random selection from a uniform distribution across the forest for its x and y coordinates. The only restriction should be that a new tree object can’t be placed in the same cell as another living tree (trees start out alive).

> How many trees? I’m currently setting that as a constant, but it’s probably better to treat it as a calculation from a starting tree density constant (% of cells with a living tree) set by the user. Tree density is an emergent property of Forest that doesn’t exist at lower levels and will change throughout the simulation as trees die and grow.

> How old is each tree? Most attributes in the game are set using a random selection from a normal distribution with a defined mean value and standard deviation. Age could be the same. So for example, a mean value of 10.0 years with a standard deviation of 4.0 years for age. It could eventually get more complicated than that (e.g. different distributions for different species or old growth vs. new growth).

**Comment by rogerhurwitz** [comment]
It looks like we need to make three statistical calculations at this stage.  @nahurwitz please review [scipy.stats](https://docs.scipy.org/doc/scipy-0.14.0/reference/stats.html), and if possible, document the needed formulas in terms of that library.

1. Where are the trees?   Assuming a grid of cells, how should the "uniform distribution across the forest for its x and y coordinates" be calculated?
2. How many trees? Is the % of cells with a living tree as simple as "if there are 200 cells, and the specified percentage is .25 then there are 50 trees in the forest?  If so, what is the default % if the value is unspecified?
3. How old is each tree?  I would be surprised if scipy.stats does not have a single function for this (truncnorm?).  If so, what is it?  If not, how should be implemented based on scipy.stats primitives?

**Comment by nahurwitz** [comment]
# <= tree density for tree location method 2.

**Comment by rogerhurwitz** [comment]
```
self.age = norm.rvs(loc=cfg["tree"]["age_mean"],
    scale=cfg["tree"]["age_sd"])
```

Almost works like a champ: approximately 2/3 of all values fall w/in 1 sd of mean, but can have outliers below zero, for example.  ``truncnorm`` solves this problem, but @nahurwitz needs to specify upper and lower age bounds.

I added a configuration file to the project (arborlife.yml) that I'm using for program-wide defaults:
```
# 
# Per object default settings for arborlife
#
tree:
  # Set initial tree age within a normal distribution
  age_mean: 10.0
  age_sd: 4.0
  # Whether a tree starts out as alive or dead
  alive: True
```

**Comment by rogerhurwitz** [comment]
Completed initial implementation of Forest along w/ associated Tile class representing the smallest x/y addressable location within the forest.  Switched from "Cell" to "Tile" to avoid possible confusion over a forest cell and a biological cell in a tree, for example.  Trees are allocated to tiles in the forest using @nahurwitz method #2 above.
