### ISSUE TITLE
Tree Dimensions

### ISSUE THREAD

**Issue by nahurwitz** [rogerhurwitz/arborlife#6]
If you want to start in on calculating tree dimensions (including root system radius) based on its canopy mass and a few other set characteristics, here's the method I'm using in the Tree class. I'm starting with an initial canopy mass average for young trees as 60 kgs that results in a height of about 10'. 

The code references a utility method that solves a cubic equation to get at the trunk diameter, but other than that, it contains relatively straightforward calculations.

            // Calculate DBH, height, bark area, canopy width, and root volume based on canopy mass and full leafing out / root mass
            public void Calc_Dimensions()
            {
                float D2H, GWT, x;
                EqSolve es = new EqSolve();

                // Determine green weight
                GWT = canopy_mass + (max_leaf_canopy_pct * canopy_mass);

                // Calculate trunk diameter, height, bark square footage, and canopy width
                D2H = (float)Math.Pow(GWT / Globals.GWT_DBH_H_coefficient, 1f / Globals.GWT_DBH_H_exp);
                x = es.Cubic(Globals.DBH_H_b1 / 12f, Globals.DBH_H_b0 / 12f, 0, -D2H);
                trunk_diameter = x;
                height = Math.Max(height, (Globals.DBH_H_b0 + Globals.DBH_H_b1 * x) / 12f);
                bark_ft2 = (float)(height * 2 * Math.PI * ((trunk_diameter / 12) / 2));
                canopy_width = Globals.height_width_ratio * height;
                root_radius = ((root_mass / canopy_mass) / root_canopy_pct_mean) * canopy_width;
                root_area = (float)Math.PI * root_radius * root_radius;
                root_ft3 = (float)(root_mass / wood_density_lb);
            }

    public float Cubic(float a, float b, float c, float d)
    {
        float p, q, r, x;

        p = -b / (3 * a);
        q = (float)(Math.Pow(p, 3) + (b * c - 3 * a * d) / (6 * Math.Pow(a, 2)));
        r = c / (3 * a);

        x = (float)(Math.Pow(q + (Math.Pow(Math.Pow(q, 2) + (Math.Pow(r - Math.Pow(p, 2), 3)), 0.5)), 1f / 3f) +
                    Math.Pow(q - (Math.Pow(Math.Pow(q, 2) + (Math.Pow(r - Math.Pow(p, 2), 3)), 0.5)), 1f / 3f) + p);

        return x;
    }

**Comment by rogerhurwitz** [comment]
All dimensions listed in the issue are implemented and tested.  Waiting on @nahurwitz to review and assess on [this proposed alternative](https://docs.scipy.org/doc/numpy/reference/generated/numpy.roots.html) to cubic function.
